"""cascade_delete_answer

Revision ID: 0fe27ed9b407
Revises: b5acbf239dd9
Create Date: 2025-09-19 18:05:51.429862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fe27ed9b407'
down_revision: Union[str, Sequence[str], None] = 'b5acbf239dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answer_question_id_fkey'), 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(op.f('answer_question_id_fkey'), 'answer', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
